PREFIX np: <http://www.nanopub.org/nschema#>
PREFIX iv: <http://bio2rdf.org/irefindex_vocabulary:>
PREFIX pav: <http://purl.org/pav/2.0/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>

insert{
  GRAPH ?nanopub
  {
    ?nanopub a np:Nanopublication ;
             np:hasAssertion ?assertionGraph ;
             np:hasProvenance ?provenanceGraph ;
             np:hasPublicationInfo ?publicationInfoGraph .
    ?assertionGraph a np:Assertion .
    ?provenanceGraph a np:Provenance .
    ?publicationInfoGraph a np:PublicationInfo .
  }
  GRAPH ?assertionGraph
  {   
    ?interaction a ?interaction_type ;
                 a sio:SIO_000897;
                 iv:interactor_a ?a ;
                 iv:interactor_b ?b ;
                 sio:has-participant ?a ;
                 sio:has-target ?b .
    ?interaction_type rdfs:label ?typelabel .
    ?a rdf:type ?a_type .
    ?a_type dcterms:title ?a_type_title .
    ?b rdf:type ?b_type .
    ?b_type dcterms:title ?b_type_title .
  }
  GRAPH ?provenanceGraph
  {
    ?assertionGraph prov:wasGeneratedBy [   
                    a prov:Activity, ?method
    ].
    # specific paper (sio_000772: has evidence)
    ?assertionGraph sio:SIO_000772 ?article .  
    # specific source (sio_000253: has source)
    ?assertionGraph sio:SIO_000253 ?dataset . 
  }
  GRAPH ?publicationInfoGraph
  {
  ?nanopub pav:authoredBy <http://tw.rpi.edu/web/person/RuiYan> ;
            pav:createdBy <http://tw.rpi.edu/web/person/RuiYan> ;
            dcterms:created ?now ;
            dcterms:rights <http://opendatacommons.org/licenses/odbl/1.0/> ; 
            dcterms:rightsHolder <http://tw.rpi.edu> .
  }
}

where{
     # bio2rdf iRefindex endpoint
     #service <http://cu.irefindex.bio2rdf.org/sparql> {  
     # openlife iRefindex endpoint
     #service <http://beta.openlifedata.org/irefindex/sparql> {
      service <http://localhost:8080/bigdata/sparql> {
        select distinct ?interaction ?interaction_type ?a ?a_type ?a_type_title ?b ?b_type ?b_type_title ?method ?article ?dataset #?interaction_label
        where { 
          {
             select distinct *
             where {
                # info of interaction a
                ?interaction iv:interactor_a ?a .
                ?a a ?a_type .
                ?a_type dcterms:title ?a_type_title .
                
                #info of interaction b
                ?interaction iv:interactor_b ?b .
                ?b a ?b_type .
                ?b_type dcterms:title ?b_type_title .

                # info of interaction itself
                ?interaction a ?interaction_type .
                FILTER REGEX(?interaction_type, "^.*?(?<!Resource)$", "i") 
                ?interaction_type rdfs:label ?typelabel.
                #?interaction rdfs:label ?interaction_label .
                
                #provinance
                ?interaction iv:method ?method .
                ?interaction iv:article ?article .
                ?interaction void:inDataset ?dataset .
             }
             #order by ?interaction
          }             
        }
       limit 10000
       offset 
}
  BIND(iri(concat(str(?interaction),"_nanopub")) as ?nanopub)
  BIND(iri(concat(str(?nanopub),"_assertion")) as ?assertionGraph)
  BIND(iri(concat(str(?nanopub),"_provenance")) as ?provenanceGraph)
  BIND(iri(concat(str(?nanopub),"_publicationInfo")) as ?publicationInfoGraph)
  BIND(NOW() as ?now)
} 
