#--------------------------------------------------------------------------------------------
# version 1.0
#
#############################################################################################

prefix fn: <http://www.w3.org/2005/xpath-functions#>
PREFIX pav: <http://purl.org/pav/2.0/>
prefix sio: <http://semanticscience.org/resource/>
prefix prov: <http://www.w3.org/ns/prov#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
prefix nanopub: <http://www.nanopub.org/nschema#>

insert {
	graph ?nanopub{
        ?nanopub a nanopub:Nanopublication .
        ?nanopub nanopub:hasAssertion ?assertion .
        ?nanopub nanopub:hasProvenance ?provenance .
        ?nanopub nanopub:hasPublicationInfo ?publicationInfo .
        ?provenance nanopub:hasAttribution ?attribution .
        ?assertion a nanopub:Assertion .
        ?provenance a nanopub:Provenance .
        ?publicationInfo a nanopub:publicationInfo .
        ?attribution a nanopub:Attribution .
	}
	graph ?assertion{

	}
	graph ?provenance{

	}
	graph ?attribution{
	    ?assertion prov:wasQuotedFrom <http://download.bio2rdf.org/current/omim/>.
	    <http://download.bio2rdf.org/current/omim/> rdfs:label "OMIM".
	}
	graph ?publicationInfo{
        ?nanopub pav:authoredBy <http://tw.rpi.edu/web/person/RuiYan> ;
                 pav:createdBy <http://tw.rpi.edu/web/person/RuiYan> ;
                 dcterms:created ?now ;
                 dcterms:rights <http://opendatacommons.org/licenses/odbl/1.0/> ; 
                 dcterms:rightsHolder <http://tw.rpi.edu> .	
	}
}
where {
	service <http://localhost:8890/sparql> {

	}
    BIND(iri(fn:concat(?interaction,"/nanopub")) as ?nanopub)
    BIND(iri(fn:concat(?interaction,"/nanopub/assertion")) as ?assertion)
    BIND(iri(fn:concat(?interaction,"/nanopub/provenance")) as ?provenance)
    BIND(iri(fn:concat(?interaction,"/nanopub/attribution")) as ?attribution)
    BIND(iri(fn:concat(?interaction,"/nanopub/publicationInfo")) as ?publicationInfo)
    BIND(NOW() as ?now)
}