PREFIX np: <http://www.nanopub.org/nschema#>
PREFIX ov: <http://bio2rdf.org/omim_vocabulary:>
PREFIX pav: <http://purl.org/pav/2.0/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>

insert{
	GRAPH ?nanopub
	{
    ?nanopub a np:Nanopublication ;
             np:hasAssertion ?assertionGraph ;
             np:hasProvenance ?provenanceGraph ;
             np:hasPublicationInfo ?publicationInfoGraph .
    ?assertionGraph a np:Assertion .
    ?provenanceGraph a np:Provenance .
    ?publicationInfoGraph a np:PublicationInfo .
	}
	GRAPH ?assertionGraph
	{
	  #info on interaction
    ?phenotype_map a sio:SIO_000897;
                   sio:has-participant ?gene_uniprot ;
                   sio:has-target ?phenotype .

    #info on phenotype
    ?phenotype a ov:Phenotype ;
               rdfs:label ?phenotype_label,
                          ?phenotye_alternative_titel ;
               dcterms:description ?phenotype_description .

		#info on gene
		?gene_uniprot a ov:Protein .
		?gene_uniprot sio:has-phenotype ?phenotype.
	}
	GRAPH ?provenanceGraph
	{
		?assertionGraph sio:SIO_000772 ?pubmed . # specific paper
		?assertionGraph sio:SIO_000253 ?dataset . # specific dataset
    ?assertionGraph prov:wasGeneratedBy [   
                 a prov:Activity, ?method
                ].                
	}
	GRAPH ?publicationInfoGraph
	{
   ?nanopub pav:authoredBy <http://tw.rpi.edu/web/person/RuiYan> ;
            pav:createdBy <http://tw.rpi.edu/web/person/RuiYan> ;
            dcterms:created ?now ;
            dcterms:rights <http://opendatacommons.org/licenses/odbl/1.0/> ; 
            dcterms:rightsHolder <http://tw.rpi.edu> .
	}
}
where{
   service <http://cu.omim.bio2rdf.org/sparql> {  
      select distinct ?phenotype ?phenotype_map ?phenotype_label ?phenotype_description ?phenotye_alternative_title ?gene_uniprot ?pubmed ?dataset ?method 
      where{
         {
            select distinct *
            where {
                #info on interaction
                ?phenotype ov:phenotype-map ?phenotype_map .

                #info on phenotype
                ?phenotype a ov:Phenotype .
                ?phenotype rdfs:label ?phenotype_label .
                ?phenotype dcterms:description ?phenotype_description .
                ?phenotype ov:alternative-title ?phenotye_alternative_title .

                #info on gene
                ?phenotype_map ov:geneSymbols ?gene_hgnc_symbol .
                ?gene_omim ov:gene-symbol ?gene_hgnc_symbol .
                ?gene_omim ov:x-uniprot ?gene_uniprot.

                #provenance
                ?phenotype ov:article ?pubmed. 
                ?phenotype void:inDataset ?dataset .
                ?phenotype_map ov:mapping-method ?method .
            }
            order by ?phenotype_map
         }
      }
      limit 10000
      offset  
  }
 	BIND(iri(concat(str(?association),"_nanopub")) as ?nanopub)
	BIND(iri(concat(str(?nanopub),"_assertion")) as ?assertionGraph)
	BIND(iri(concat(str(?nanopub),"_provenance")) as ?provenanceGraph)
	BIND(iri(concat(str(?nanopub),"_publicationInfo")) as ?publicationInfoGraph)
	BIND(NOW() as ?now)
}
